### ISSUE TITLE
Tracking issue for TI bq769x2 support

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/bms-firmware#24]
This issue gives an overview of the implementation status for the Texas Instruments bq76952 / bq76942 BMS IC support in the BMS firmware.

- [x] Communication interface: Direct commands
- [x] Communication interface: Subcommands
- [x] Voltage reading
- [x] Current reading
- [x] Temperature reading
- [x] Error reading
- [x] Charge/discharge MOSFET switching
- [x] Balancing
- [x] Short-circuit protection
- [x] Overcurrent protection in discharge direction
- [x] Overcurrent protection in charge direction
- [x] Cell undervoltage protection
- [x] Cell overvoltage protection
- [x] Temperature protection
